CREATE DATABASE ACADEMIA

USE ACADEMIA

CREATE TABLE aluno (
  matricula INT NOT NULL,
  nome VARCHAR(100) NOT NULL,
  data_nascimento DATE NOT NULL,
  email VARCHAR(100),
  cpf VARCHAR(14) NOT NULL,
  celular VARCHAR(15) NOT NULL,
  PRIMARY KEY (matricula)
);

CREATE TABLE mensalidade (
  descricao VARCHAR(100) NOT NULL,
  valor FLOAT NOT NULL,
  caracteristica VARCHAR(100) NOT NULL
);

CREATE TABLE ACADEMIA (
	RAZAO_SOCIAL VARCHAR(100) NOT NULL,
	CNPJ CHAR(14) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	ESTADO VARCHAR(100) NOT NULL,
	TELEFONE CHAR(9)
);

CREATE TABLE PROFESSOR (
	CODIGO INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(100),
	CPF CHAR(14) NOT NULL,
	CELULAR CHAR(9) NOT NULL,
	CREF CHAR(6) NOT NULL
);

CREATE TABLE FICHA (
	NOME_ALUNO VARCHAR(100) NOT NULL,
	NOME_PROFESSOR VARCHAR(100) NOT NULL,
	EXERCICIO VARCHAR (100) NOT NULL,
	REPETICOES INT NOT NULL,
	PESO FLOAT
);

CREATE TABLE CIDADE(
	CODIGO INT NOT NULL
		CONSTRAINT PK_CIDADE PRIMARY KEY,
	NOME VARCHAR(10) NOT NULL
);

CREATE TABLE PESSOA(
	CODIGO INT NOT NULL PRIMARY KEY,
	CPF CHAR(11) NOT NULL
		CONSTRAINT UN_PESSOA_CPF UNIQUE,
	CIDADE INT NOT NULL
		CONSTRAINT FK_PESSOA_CIDADE FOREIGN KEY
		REFERENCES CIDADE(CODIGO)
);

CREATE TABLE FUNCIONARIO(
	MATRICULA INT NOT NULL
		CONSTRAINT PK_FUNCIONARIO PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF CHAR(11) NOT NULL
		CONSTRAINT UN_FUNCIONARIO_CPF UNIQUE,
	NACIONALIDADE VARCHAR(50)
		CONSTRAINT DF_FUNCIONARIO_NACIONALIDADE DEFAULT 'BRASIL'
);
